workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      xcode: latest

    scripts:
  - name: Install dependencies
    script: npm install
  - name: Build Vite app
    script: npm run build
  - name: Add iOS platform
    script: npx cap add ios
  - name: Sync Capacitor
    script: npx cap sync ios
  - name: Install CocoaPods
    script: |
      cd ios/App
      pod install --repo-update
      cd ../..

    artifacts:
      - ios/build/**/*.ipa
